eureka:
  client:
    healthcheck: true
    service-url:
      defaultZone: http://localhost:9000/eureka
server:
  port: 9003
spring:
  application:
    name: ServiceB
management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
