server:
  port: 9001
  tomcat:
    max-threads: 2000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
#ribbon:
#  ReadTimeout: 30000
#  SocketTimeout: 30000

zuul:
  ignored-services: '*'
  routes:
    servicea:
      path: /a/**
      serviceId: servicea
    serviceb:
      path: /b/**
      serviceId: serviceb
  semaphore:
    max-semaphores: 1000
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 65000
  threadpool:
#    servicea:
#      coreSize: 20
#    serviceb:
#      coreSize: 20
    default:
      allowMaximumSizeToDivergeFromCoreSize: true
      coreSize: 20
      maximumSize: 50
      maxQueueSize: 10
      queueSizeRejectionThreshold: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
spring:
  application:
    name: "gateway"
  rabbitmq:
    host: common-server
    username: admin
    password: admin
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      addresses: common-server