

eureka:
  client:
    healthcheck: true
    service-url:
      defaultZone: http://localhost:9000/eureka
server:
  port: 9002
  tomcat:
    max-threads: 2000
spring:
  application:
    name: ServiceA
  rabbitmq:
    host: common-server
    username: admin
    password: admin
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      addresses: common-server
prop: hamid
management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"